### PR TITLE
Task 4 (After Lecture4 "Cloud Databases Overview Overview of DB solutions (SQL, No-SQL (Dynamodb, Mongo, Redis, Elastic Search), NewSQL) Infrastructure As Code (IaC), deployment sample to deploy RDS")

### PR DESCRIPTION
**Pull request by aleksandr-zharov**
TASK 4.1
image
image

TASK 4.2
  GET - https://djdaxun8fl.execute-api.eu-west-1.amazonaws.com/dev/products/{id}
  GET - https://djdaxun8fl.execute-api.eu-west-1.amazonaws.com/dev/products

TASK 4.3
  POST - https://djdaxun8fl.execute-api.eu-west-1.amazonaws.com/dev/products

Check FE:
https://dndbrxqx66t48.cloudfront.net/

+1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
+1 - All lambdas do console.log for each incoming requests and their arguments
+1 - Transaction based creation of product 
+1 - POST/products lambda functions returns error 400 status code if product data is invalid

SWAGGER:
https://editor.swagger.io/?url=https://raw.githubusercontent.com/aleksandr-zharov/nodejs-aws-backend/997a4cdbc018920a0b3892f02b3993eb20dd9557/product-service/swagger/openapi.yaml

### CODE REVIEW

**Comment by shurygindv** [comment]
seems POST /products doesn't work as expected when sending such model

{
**"count"**: 344,
**"description"**: "some content",
**"price"**: 34344,
**"title"**: "some title"
}

got: `{
  "message": "error: null value in column \"name\" violates not-null constraint"
}`

**Comment by ilya-moskovtsev** [comment]
> Check FE:
> https://dndbrxqx66t48.cloudfront.net/

I couldn't add a new product via the front-end.

**Review by ilya-moskovtsev — APPROVED** [review]

**Review by shurygindv — APPROVED** [review]

**Comment by aleksandr-zharov** [comment]
> > Check FE:
> > https://dndbrxqx66t48.cloudfront.net/
> 
> I couldn't add a new product via the front-end.

Thanks. Fixed

**Comment by aleksandr-zharov** [comment]
> @aleksandr-zharov, seems POST /products doesn't work as expected when sending such model
> 
> {
> **"count"**: 344,
> **"description"**: "some content",
> **"price"**: 34344,
> **"title"**: "some title"
> }
> 
> got: `{ "message": "error: null value in column \"name\" violates not-null constraint" }`
> 
> so ambiguous product model with `gender` and `size` ))
> https://github.com/aleksandr-zharov/nodejs-aws-backend/blob/5fc50f2807dd38a0b488ca7e118060fdd41b30c2/product-service/services/products.ts#L49

Thanks. Fixed. Added Joi for this purpose.

https://editor.swagger.io/?url=https://raw.githubusercontent.com/aleksandr-zharov/nodejs-aws-backend/997a4cdbc018920a0b3892f02b3993eb20dd9557/product-service/swagger/openapi.yaml

**Review by Shestak2039 — APPROVED** [review]

**Comment by ilya-moskovtsev** [comment]
> I didn't add `create product` to UI because it's not required in Task4.

I do believe it is required.
"5 - Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer."
/products API includes POST method now, therefore I should be able to add a product on the front-end https://dndbrxqx66t48.cloudfront.net/admin/product-form/

**Pull request merged**
